// react-client/src/Components/Views/Services.js
import React, { Component } from 'react';
import Carousel from '../Carousel';
import TabNavigator from '../TabNavigator'

//images
import preDesign from '../../img/services/services-tab-pre-construction-img.png';

class Services extends Component {
  render() {
        let tabs = ['Pre-Construction', 'Construction', 'Design Build', 'Sustainability'];
    return (
        <div className="services">
            <Carousel title="Services" />
            <section className="main-content">
			<div className="heading-text">
					<p>Services include: completely synergize resource taxing relationships via premier niche markets. Professionally cultivate one-to-one customer service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer service.</p>
			</div>

			<TabNavigator tabs={tabs}>
			    <div className="tab-contents">
			    	<div className="tab-content" data-tab="1">
			    		<h2>Pre-Construction</h2>
			    		<div className="content">
			    			<div className="text">
			    				<p>Completely synergize resource taxing relationships via premier niche markets. Professionally cultivate one-to-one customer service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer service.</p>
			    				<p>Phosfluorescently engage worldwide methodologies with web-enabled technology. Interactively coordinate proactive e-commerce via process-centric "outside the box" thinking. Completely pursue scalable customer service through sustainable potentialities.</p>
			    			</div>
			    			<div className="image">
			    				<img src="./img/services/services-tab-pre-construction-img.png" alt="Construction" className="desktop-image" />
			    				<img src="./img/services/services-tab-mobile-pre-construction-img.png" alt="Construction" className="mobile-image" />
			    			</div>
			    		</div>
			    	</div>
			    	<div className="tab-content" data-tab="2">
			    		<h2>Construction</h2>
			    		<div className="content">
			    			<div className="text">
			    				<p>Completely synergize resource taxing relationships via premier niche markets. Professionally cultivate one-to-one customer service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer service.</p>
			    				<p>Phosfluorescently engage worldwide methodologies with web-enabled technology. Interactively coordinate proactive e-commerce via process-centric "outside the box" thinking. Completely pursue scalable customer service through sustainable potentialities.</p>
			    			</div>
			    			<div className="image">
			    				<img src="./img/services/services-tab-construction-img.png" alt="Construction" className="desktop-image" />
			    				<img src="./img/services/services-tab-mobile-construction-img.png" alt="Construction" className="mobile-image" />
			    			</div>
			    		</div>
			    	</div>
			    	<div className="tab-content" data-tab="3">
			    		<h2>Design Build</h2>
			    		<div className="content">
			    			<div className="text">
			    				<p>Completely synergize resource taxing relationships via premier niche markets. Professionally cultivate one-to-one customer service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer service.</p>
			    				<p>Phosfluorescently engage worldwide methodologies with web-enabled technology. Interactively coordinate proactive e-commerce via process-centric "outside the box" thinking. Completely pursue scalable customer service through sustainable potentialities.</p>
			    			</div>
			    			<div className="image">
			    				<img src="./img/services/services-tab-design-build-img.png" alt="Construction" className="desktop-image" />
			    				<img src="./img/services/services-tab-mobile-design-build-img.png" alt="Construction" className="mobile-image" />
			    			</div>
			    		</div>
			    	</div>

			    	<div className="tab-content" data-tab="4">
			    		<h2>Sustainability</h2>
			    		<div className="content">
			    			<div className="text">
			    				<p>Completely synergize resource taxing relationships via premier niche markets. Professionally cultivate one-to-one customer service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer service.</p>
			    				<p>Phosfluorescently engage worldwide methodologies with web-enabled technology. Interactively coordinate proactive e-commerce via process-centric "outside the box" thinking. Completely pursue scalable customer service through sustainable potentialities.</p>
			    			</div>
			    			<div className="image">
			    				<img src="./img/services/services-tab-sustainability-img.png" alt="Construction" className="desktop-image" />
			    				<img src="./img/services/services-tab-mobile-sustainability-img.png" alt="Construction" className="mobile-image" />
			    			</div>
			    		</div>
			    	</div>
                    
			    </div>
            </TabNavigator>
		</section>
        </div>
    );
  }
}

export default Services;

// src/components/Services.vue
<template>
<div class="container">
<div class="services">
		<p>Services include: completely synergize resource taxing relationships via premier niche markets. Professionally cultivate
			one-to-one customer service with robust ideas. Dynamically innovate resource-leveling customer service for state of the
			art customer service.</p>
	</div>

	<div class="section">
		<div class="tabs">
			<div class="tabs-links">
				<div class="tabs-link" data-tab="1">Pre-Construction</div>
				<div class="tabs-link" data-tab="2">Construction</div>
				<div class="tabs-link" data-tab="3">Design Build</div>
				<div class="tabs-link" data-tab="4">Sustainability</div>
			</div>
			<div class="tabs-items">
				<div class="tabs-item" data-tab="1">
					<div class="tabs-item-title">Pre-Construction</div>
					<div class="tabs-item-description">
						<div class="tabs-text">
							<p>
								Completely synergize resource taxing relationships via premier niche markets. Professionally cultivate one-to-one customer
								service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer
								service.<br><br> Phosfluorescently engage worldwide methodologies with web-enabled technology. Interactively coordinate proactive
								e-commerce via process-centric "outside the box" thinking. Completely pursue scalable customer service through sustainable
								potentialities.
							</p>
						</div>
						<div>
							<img class="desktop-img" src="img/services/services-tab-pre-construction-img.png" />
							<img class="mobile-img" src="img/services/services-tab-mobile-pre-construction-img.png" />
						</div>
					</div>
				</div>
				<div class="tabs-item" data-tab="2">
					<div class="tabs-item-title">Construction</div>
					<div class="tabs-item-description">
						<div class="tabs-text">
							<p>
								Completely synergize resource taxing relationships via premier niche markets. Professionally cultivate one-to-one customer
								service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer
								service.<br><br>Phosfluorescently engage worldwide methodologies with web-enabled technology. Interactively coordinate proactive
								e-commerce via process-centric "outside the box" thinking. Completely pursue scalable customer service through sustainable
								potentialities.
							</p>
						</div>
						<div>
							<img class="desktop-img" src="img/services/services-tab-construction-img.png" />
							<img class="mobile-img" src="img/services/services-tab-mobile-construction-img.png" />
						</div>
					</div>
				</div>
				<div class="tabs-item" data-tab="3">
					<div class="tabs-item-title">Design Build</div>
					<div class="tabs-item-description">
						<div class="tabs-text">
							<p>
								Completely synergize resource taxing relationships via premier niche markets. Professionally cultivate one-to-one customer
								service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer
								service. <br><br>Phosfluorescently engage worldwide methodologies with web-enabled technology. Interactively coordinate proactive
								e-commerce via process-centric "outside the box" thinking. Completely pursue scalable customer service through sustainable
								potentialities.
							</p>
						</div>
						<div>
							<img class="desktop-img" src="img/services/services-tab-design-build-img.png" />
							<img class="mobile-img" src="img/services/services-tab-mobile-design-build-img.png" />
						</div>
					</div>
				</div>
				<div class="tabs-item" data-tab="4">
					<div class="tabs-item-title">Sustainability</div>
					<div class="tabs-item-description">
						<div class="tabs-text">
							<p>
								Completely synergize resource taxing relationships via premier niche markets. Professionally cultivate one-to-one customer
								service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer
								service. <br><br>Phosfluorescently engage worldwide methodologies with web-enabled technology. Interactively coordinate proactive
								e-commerce via process-centric "outside the box" thinking. Completely pursue scalable customer service through sustainable
								potentialities.
							</p>
						</div>
						<div>
							<img class="desktop-img" src="img/services/services-tab-sustainability-img.png" />
							<img class="mobile-img" src="img/services/services-tab-mobile-sustainability-img.png" />
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
  </div>
</template>

<script type = "text/javascript" >

export default {
};
</script>

<style lang="less">
@import '../assets/mixins.less';
@import '../assets/global-styles.less';
  .services {
  padding-top: 52px;

  @media @phone {
    padding-top: 35px;
  }
  p {
    font-size: 16px;
    line-height: 25px;

    @media @phone {
      font-size: 20px;
      line-height: 33px;
    }
  }
}
.section {
  margin: 44px auto 65px auto;
  display: flex;
  overflow: hidden;

  @media @phone {
    margin: 49px auto 82px auto;
  }
}
</style>
